### ISSUE TITLE
Icons are filtered by muBlock

### ISSUE THREAD

**Issue by cpsievert** [clayh53/tufte-jekyll#1]
A style property of `style="display: none !important;"` is attached to some of the icons (for some reason this doesn't happen in Firefox)

![screen shot 2015-04-20 at 3 40 58 pm](https://cloud.githubusercontent.com/assets/1365941/7240037/d740f042-e773-11e4-9e84-19d881da5f49.png)

**Comment by clayh53** [comment]
Is the social.yml file in the '_data' folder fully filled out? I can't figure out what may be going on because it renders just fine on Chrome, Safari, IE11and Firefox on my computers.

**Comment by cpsievert** [comment]
Huh, strange, that is a screenshot of what I see here -- http://clayh53.github.io/tufte-jekyll/

I'm using Chrome 42.0.2311.90

**Comment by cpsievert** [comment]
Not sure if this is related, but I also see this error message in Firefox developer tools

![screen shot 2015-04-23 at 10 20 18 am](https://cloud.githubusercontent.com/assets/1365941/7300563/7308540e-e9a2-11e4-98a7-5a88356de6ac.png)

**Comment by clayh53** [comment]
That is really weird. Here is my screen shot from a mac osx Chrome version 42.0.2311 :

**Comment by cpsievert** [comment]
Ah, it was muBlock doing some cosmetic filtering :/

![screen shot 2015-04-23 at 10 00 06 pm](https://cloud.githubusercontent.com/assets/1365941/7311636/7724914e-ea04-11e4-9dde-134c8866ee4a.png)

**Comment by cpsievert** [comment]
Feel free to close this if you see this as an issue...
