### ISSUE TITLE
Full text-width for pages

### ISSUE THREAD

**Issue by michaellevy** [clayh53/tufte-jekyll#10]
Hi Clay, this theme is great. Thanks for putting it together. I would love to see the couple of mobile-browser issues addressed but don't have the skills to do it myself. One other suggestion is to have a full-width text option, perhaps as default for pages. If there is already an easy way to set this, I am all ears. Thanks again.

**Comment by clayh53** [comment]
I finally have some time to dust this off and fix some of the layout issues. I will push any changes up to the repo as soon as I get them done

**Comment by clayh53** [comment]
I have a full-width option in the new version
