### ISSUE TITLE
Why does the font size increase arbitrarily with window width?

### ISSUE THREAD

**Issue by reitzig** [clayh53/tufte-jekyll#11]
The CSS specifies different font sizes for different window sizes, all the way up to 17px. I understand the idea behind that in principle.

However, it doesn't stop there. In full screen on my 22'' monitor, I get 23.8pt. That's *way* too large.

Where does this come from? Where in the CSS can I prevent that from happening?

Possibly related issue: jumping floating image.

![screenshot from 2015-10-02 20 24 40](https://cloud.githubusercontent.com/assets/4246780/10254486/619e999a-6944-11e5-8886-f8b07f0078d4.png)

Make the window a tiny bit broader:

![screenshot from 2015-10-02 20 24 56](https://cloud.githubusercontent.com/assets/4246780/10254493/6a8995a0-6944-11e5-9533-22e7229f7749.png)

When I start with a narrow window and increase width all the way up to screen width, the image jumps around multiple times.

**Comment by clayh53** [comment]
You're right. It should stop. I'll check the logic on the media queries.

**Comment by clayh53** [comment]
I've made changes to the header and nav with the new version. See if it works now.
