### ISSUE TITLE
Adding a `sidenote` in a list item makes the main column narrow

### ISSUE THREAD

**Issue by quxiaofeng** [clayh53/tufte-jekyll#12]
For example,

```
{% math %}{\bf \lambda}^{(t+1)} \leftarrow {\bf \lambda}^{(t)} + \rho({\bf D\beta}^{(t)} - {\bf \gamma}^{(t)}){% endmath %}

Same algorithm applies to a general regularization matrix {%m%}{\bf D}{%em%} (generalized lasso)

## Remarks on ADMM

Related algorithms

+ Split Bregman iteration {% sidenote 1 'Goldstein, T. and Osher, S. (2009). The split Bregman method for l1-regularized problems. SIAM J. Img. Sci., 2:323-343.' %}

+ Dykstra's alternating projection algorithm {% sidenote 2 'Dykstra, R. L. (1983). An algorithm for restricted least squares regression. J. Amer. Statist. Assoc., 78(384):837-842.' %}

+ Proximal point algorithm applied to the dual

+ Numerous applications in statistics and machine learning: lasso, gen. lasso, graphical lasso, (overlapping) group lasso, ...

+ Embraces distributed computing for big data {% sidenote 3 'Boyd, S., Parikh, N., Chu, E., Peleato, B., and Eckstein, J. (2011). Distributed optimization and statistical learning via the alternating direction method of multipliers. Found. Trends Mach. learn., 3(1):1-122.' %}
```

is rendered as follows:

![qq 20151005111600](https://cloud.githubusercontent.com/assets/1077425/10272492/d286d360-6b52-11e5-82bc-3b83d415e7b1.png)

The sidenote is rendered in the env of `<ul><li><p></p></li></ul>`. The width is computed within the `<p>` env, which is only the `main column`.

The markdown code can be found in: 
https://github.com/quxiaofeng/optimization/edit/master/_posts/2015-07-18-alternating-direction-method-multipliers.md

The rendered result can be found in:
http://www.optimizations.ml/2015/07/18/alternating-direction-method-multipliers/

**Comment by clayh53** [comment]
The problem arises when  blank lines are separating list items. The Jekyll engine parses them differently. See the discussion [here](http://clayh53.github.io/tufte-jekyll/articles/15/Edge-Cases/)

**Comment by quxiaofeng** [comment]
In the index page, if the abstract of the post includes a list (`<ul><li></li></ul>`), the abstract would be still rendered as `<ul><li><p></p></li></ul>`.
