### ISSUE TITLE
The latest version renders `&` in aligned env as `amp;`

### ISSUE THREAD

**Issue by quxiaofeng** [clayh53/tufte-jekyll#14]
The latest config of mathjax does not render `<`, `>`, `&` well. The `<` and `>` can be replaced by `\lt` and `\gt` respectively. However, there is no alternative solution for `&`.

The code:

```
{% math %}
D = \left(\begin{matrix}
1 & -1 & &      &   & \\
  &    & \cdots &   & \\
  &    &        & 1 & -1
\end{matrix}
\right)
{% endmath %}
```

> line 35-41 of [this markdown](https://github.com/quxiaofeng/optimization/blame/master/_posts/2015-07-18-alternating-direction-method-multipliers.md)

will be rendered as this:

![image](https://cloud.githubusercontent.com/assets/1077425/10359538/427cac46-6dcc-11e5-8e26-a4b3094e02dd.png)

(This may be due to the mathjax env is set to centered ???)

**Comment by quxiaofeng** [comment]
Eh, the `master` branch of this repo is not working. For example, the `lata_font_load`  should be `lato_font_load` in line 14 [this page](https://github.com/clayh53/tufte-jekyll/blob/master/_includes/head.html).

**Comment by clayh53** [comment]
Fixed the typo. Will look into Mathjax

**Comment by quxiaofeng** [comment]
Thank you for your fix. If you want, you may take one of my posts as a test page (as a continuous test).

The `mathjax` is very tricky. There could be many errors there. The upgrading of the theme took much effort. One may not be willing to take the risk without a strong evidence (a post including various long and complex equations).

**Comment by clayh53** [comment]
I have made some changes that should fix the Mathjax block problems with matrices and some symbols. Bottom line is that the Kramdown parser is *very* sensitive to these custom tags. In particular, if you want your matrix notation to display properly, you must surround the '{% math %}...{%endmath%}``` with blank lines above and below the block. Also, the Mathjax documentation I referenced recommended that angle brackets should be written as ```|lt and |gt```.  One problem I have not solved is the inline matrix notation issue when using the inline tags. It simply doesn't work properly and displays the unwanted ampersands. I tried escaping them, but that just printed the ampersand and the html code entity!

**Comment by clayh53** [comment]
fixed all but inline matrix notation in Mathjax content

**Comment by xHN35RQ** [comment]
> fixed all but inline matrix notation in Mathjax content

If you're referring display of ampersands... isn't this happening because in Latex the `&` symbol is used for aligned formula? Are ampersands used in-line for formula?

> Also, the Mathjax documentation I referenced recommended that angle brackets should be written as |lt and |gt

I think that's meant to be `\lt` and `\gt` since I read that literal pipes can screw up Mathjax. I think that it's recommended to use command `\vert` instead of the actual pipe symbol of `|` but I might be wrong about this.
