### ISSUE TITLE
h3 margin-top overridden by .listing

### ISSUE THREAD

**Issue by gavinmcgimpsey** [clayh53/tufte-jekyll#18]
```margin-top``` is set in tufte.scss, but later, ```.listing .listing h3``` overrides it with a generic ```margin: 0;```

Subheadings on posts have no top margin separating them from headings or previous paragraphs.

**Comment by clayh53** [comment]
this margin is only used for the entry listing page to close up the space between post's listings. It should not apply to anything that is not a h3 descendent of an .listing class. On my builds, the headings spacings for a post seems to display properly. Let me know if you find anything different.

**Comment by xHN35RQ** [comment]
Was this a by-product of accidentally leaving tufte.css in the repo?

**Comment by clayh53** [comment]
Possibly. I didn't understand about how the Jekyll pipeline worked with SCSS files initially. I had been using Codekit.

**Comment by xHN35RQ** [comment]
It's around th esame time period... and it seems like a conflict that might arise from having 2 CSS sources.

**Comment by clayh53** [comment]
Think this was the CSS problem. Closing for now.
