### ISSUE TITLE
Auto travis build config?

### ISSUE THREAD

**Issue by quxiaofeng** [clayh53/tufte-jekyll#2]
Could this tufte-jekyll theme be build automatically by travis?

I am using Windows for daily work. It is a painful task to start the Ubuntu virtual machine to build the site and upload. Although the rakefile is well written to build and upload the site to `gh-pages` branch automatically, the building is still required. If it can be configured in a Travis config file, this task can be simplified into `git push` the source files only. Moreover, this simple task can be done platform independently. Even can be done by modifying the file using Github online edit-and-commit function, which can be done on a smartphone when out of office.

There is a problem that I am not familiar with the plugins and dependencies this theme required. Could you please make this task possible?

There is a project in GitHub about how to config Travis for Rake and Jekyll: https://github.com/mfenner/jekyll-travis. Hope it will help.

**Comment by quxiaofeng** [comment]
I managed to make the travis work. Just list it here.

The configuration is super easy. The core script is only several lines long.

```
before_install:
- gem install rouge

install:
- gem install jekyll

# Notice: Replace 'YOUR NAME' and 'YOUR EMAIL'
before_script:
- git config --global user.name 'Your Name'
- git config --global user.email 'your@email.address'

script:
- jekyll build
```

The full `.travis.yml` file can be found [here](https://github.com/quxiaofeng/optimizations.ml/blob/master/.travis.yml). Basically clone the `master` branch, build, copy generated files to another folder, clone the `gh-pages` branch, commit and push.

Thank you for your awesome theme.

**Comment by clayh53** [comment]
Thanks! I will add that to the repo with your instructions.
