### ISSUE TITLE
Underline links in header and tittles.

### ISSUE THREAD

**Issue by gperaza** [clayh53/tufte-jekyll#21]
Hi, I was testing the underline option for the links, and using it make links in the header and post tittles on the front page to be also underlined. I don't know if this is intentional but I think it should only change the links in the text body if possible.
Thanks.

**Comment by clayh53** [comment]
Yep, you are right. I will fix that with ```p > a``` specifier in the CSS

**Comment by clayh53** [comment]
It's fixed now. Good catch. Thanks!
