### ISSUE TITLE
Fullwidth captions don't expand link syntax

### ISSUE THREAD

**Issue by niallrmurphy** [clayh53/tufte-jekyll#23]
So, e.g. {% fullwidth 'blah/img/blah' 'Hi there this is a [source](http://wibble)' %} will just be printed as plain text.

**Comment by xHN35RQ** [comment]
Is the fullwidth tag on it's own line? It needs to be the only text on that line in your Markdown document.

```
blah blah

{% fullwidth 'assets/img/rhino.png' 'A caption for the image' %}

blah blah
```

**Comment by niallrmurphy** [comment]
Source HTML looks like:

The source code looks something like this:

"""
<p></p>

{% fullwidth 'assets/img/internet_eireann_feb_1995_p.jpeg' "A 1995 paper leaflet advertising IE's services (via <http://brandnewretro.ie/2012/08/23/old-adverts-88-internet-eireann-1995/>" %}

This leaflet advertises a number of wonderful facilities, ...
"""

which results in the following screenshot:

https://www.dropbox.com/s/6yv8nm1qne8hqno/Screenshot%202015-12-31%2023.42.08.png?dl=0

(in this screenshot I use the <link> syntax, but it was the same when it was []()

**Comment by clayh53** [comment]
And that looks like we need to use something to clear the float on that full-width image. 

I hope everyone realizes that this CSS came from the Tufte-CSS repo. 

If I had written it all, it would be much, much worse.

**Comment by xHN35RQ** [comment]
@niallrmurphy try escaping your apostrophe

```
{% fullwidth 'assets/img/internet_eireann_feb_1995_p.jpeg' "A 1995 paper leaflet advertising IE's services (via http://brandnewretro.ie/2012/08/23/old-adverts-88-internet-eireann-1995/" %}

This leaflet advertises a number of wonderful facilities, ...
```

**Comment by xHN35RQ** [comment]
@clayh53 I think this is just a matter of proper escaping... should probably add something to the Readme about that. I forgot to do so when I submitted the plugin patches.

**Comment by niallrmurphy** [comment]
Thank you gentlemen for your excellent support!

**Comment by niallrmurphy** [comment]
Hmm, nope.. seems like it just prints:

A 1995 paper leaflet advertising IE's services (via [brandnewretro](http://brandnewretro.ie/2012/08/23/old-adverts-88-internet-eireann-1995/).

It doesn't seem to spot the []() syntax even after escaping the quote (with \ to be clear).

**Comment by xHN35RQ** [comment]
Please try this line and tell me what happens

```{% fullwidth "assets/img/internet_eireann_feb_1995_p.jpeg" "A 1995 paper leaflet advertising IE&#39;s services (via http://brandnewretro.ie/2012/08/23/old-adverts-88-internet-eireann-1995/)" %}
```

**Comment by niallrmurphy** [comment]
Nope, sorry; quote gets rendered okay (as it has been the past few iterations) but no link. It's as if the line is not being passed to the markdown parser or is not exiting it with the link correctly identified...

**Comment by xHN35RQ** [comment]
Interesting. can you upload the exact image somewhere for me? I'll prep a fresh jekyll build and test with your image & tag.

**Comment by niallrmurphy** [comment]
https://www.dropbox.com/s/y2mitrk7bh13zwg/Screenshot%202016-01-01%2010.34.34.png?dl=0

Surrounding code is now:

Internet Éireann made some crucial decisions at the right time: they were betting on a growth market, which it was, and an ability to sweat their assets. In the mid-1990s ISP business, this meant running their modem pool "hot", i.e. having too few of them for the number of customers, as discussed above. It was a straightforward value-for-money consumer play, whose appeal was certainly based on cost, but also the even then staggeringly large array of services available to anyone at the other end of a dial-up connection. (See, for example, the below image, which shows a leaflet advertising Internet Éireann’s services.)

<p></p>

{% fullwidth "assets/img/internet_eireann_feb_1995_p.jpeg" "A 1995 paper leaflet advertising IE&#39;s services (via http://brandnewretro.ie/2012/08/23/old-adverts-88-internet-eireann-1995/)" %}

This leaflet advertises a number of wonderful facilities, the majority of which have now perished, or been swallowed up by the hypergrowth of the web in general: “File Transfer”, “Telnet”, “Archie”, “Gopher”, and so on.

**Comment by xHN35RQ** [comment]
Thanks! I'll test right now on a fresh install. I'm curious why this isn't working. :wink:

**Comment by xHN35RQ** [comment]
Ok, I was wrong, you usually don't need to escape anything. The Liquid plugins for Jekyll are intelligent enough that if you use double quotes, it auto-escapes single quotes. Or if you use single quotes, it should auto-escape double quotes.

For example, using the following tag:

```
{% fullwidth "assets/img/rhino.png" "A 1995 paper leaflet advertising IE's services (via http://brandnewretro.ie/2012/08/23/old-adverts-88-internet-eireann-1995/)" %}
```
This is my result: 

http://fullwidthtest.surge.sh/test/

However as you can see the captions are not clearing properly. They don't clear properly in any of the page layouts (page, post or full-width) @clayh53 I wonder if this has been fixed upstream in [`tufte-css`](https://github.com/edwardtufte/tufte-css)

**Comment by niallrmurphy** [comment]
Yep, I see; does it link-ify for you if you use angle brackets or the []() notation as a matter of interest?

**Comment by xHN35RQ** [comment]
Aha, I've got a sort-of okay CSS fix for this:

```
figure.fullwidth figcaption {
  margin-right: 0%;
  max-width: 100%;
  margin-left: 28%;
}
``` 
Check it out: http://fullwidthtest.surge.sh/test/

And @niallrmurphy nope these Liquid tags are passing the raw text directly to the Jekyll engine, you can't use Markdown in these tags. If you want to have it be a link you'll need to write out the HTML for it, and escape the double quotes in the href tag, like so:

```
{% fullwidth "assets/img/rhino.png" "A 1995 paper leaflet advertising IE's services (via <a href=\"http://brandnewretro.ie/2012/08/23/old-adverts-88-internet-eireann-1995/\">http://brandnewretro.ie/2012/08/23/old-adverts-88-internet-eireann-1995/</a>)" %}
```

**Comment by niallrmurphy** [comment]
Understood, thanks!

**Comment by xHN35RQ** [comment]
Here's what I think is a good fix, put this into your `tufte.scss` and replace the existing entry for `figure.fullwidth figcaption`
```
figure.fullwidth figcaption {
  float: left;
  margin-right: 0%;
  margin-left: 36%;
}
```
Here's a preview: http://fullwidthtest.surge.sh/test/

**Comment by niallrmurphy** [comment]
Excellent, thanks!

**Comment by xHN35RQ** [comment]
Cool, if this is fixed for you feel free to close the issue. I put in a pull request #26 to help fix this issue.

**Comment by clayh53** [comment]
Thanks Nick. I have merged the pull request into the master.

I appreciate the help on this.

**Comment by xHN35RQ** [comment]
Thanks, and You're welcome!
