### ISSUE TITLE
A sidenote in a blockquote is pulled in further than it should be from the right hand margin

### ISSUE THREAD

**Issue by niallrmurphy** [clayh53/tufte-jekyll#24]

**Comment by xHN35RQ** [comment]
Please provide more explanation, and maybe a screenshot. How much further in is the sidenote pulled from the right hand margin? What should it be? And how does it appear for you?

**Comment by niallrmurphy** [comment]
Certainly, sorry. Have a look at the following screenshot:

https://www.dropbox.com/s/mdbcr499jim4izb/Screenshot%202015-12-31%2023.28.25.png?dl=0

You'll see that the bottom half of the screen contains a sidenote which is left-shifted compared to the sidenote visible at the right-hand side.

**Comment by clayh53** [comment]
Yep, that is a problem. I'm guessing it has something to with the margin being calculated from the parent element (in this case, the indented blockquote). I'll see if I can figure out how to get that fixed. And of course, anybody else reading this that has already figured it out: please submit the fix and I'll get the repo modified appropriately.

-Clay

**Comment by xHN35RQ** [comment]
Marginnotes have the same issue. Increasing the negative `margin-right` should fix it.

**Comment by xHN35RQ** [comment]
Yep, adding this fixes it:

```
blockquote .sidenote, blockquote .marginnote {
  margin-right: -79%
}
```

**Comment by clayh53** [comment]
Should be fixed now.
