### ISSUE TITLE
Update readme with proper use of quotes in Liquid tags

### ISSUE THREAD

**Issue by xHN35RQ** [clayh53/tufte-jekyll#25]
see #23 

I'll do this in a separate PR from #26

**Comment by xHN35RQ** [comment]
- [ ] update readme to use double quotes in tag examples
- [ ] add note on quoting priority: quote first > single quote > escaped quotes

**Comment by clayh53** [comment]
Updated README.md, but for some strange reason it is changed in the repo, but not in the main page for this repo! Maybe it has to propagate through some Github cache busting thing. I dunno. But if you click on the README.md, it has the updated verbiage. The sample site has also been updated with the example in the Edge-Cases blog entry.

**Comment by xHN35RQ** [comment]
Thanks for adding that to the Readme. I have some modifications to make based on testing the code, so please re-open this issue and when I have time, I'll propose a PR with my edits. Thanks again!

**Comment by xHN35RQ** [comment]
done
