### ISSUE TITLE
Single markdown linebreaks cause <br>

### ISSUE THREAD

**Issue by mkirchner** [clayh53/tufte-jekyll#31]
In the default setup `tufte-jekyll` is configured to put newlines where the original markdown had a single line word wrap. This forces users to use long lines (very inconvenient for versioning) and comes as a bit of a surprise as this is not the standard for most markdown interpreters.

The solution is to manually disable the `hard_wrap` option of `kramdown` in `_config.yml` like so:

        markdown: Kramdown
        kramdown:
            ...
            input: GFM
            hard_wrap: false  <-- here
            ...

Would you mind bringing that option into `_config.yml` either as a default or commented out (as it is likely a breaking change for existing blogs)? Anything that helps the next person figuring this out faster would be greatly appreciated. Thanks!

**Comment by xHN35RQ** [comment]
Or you could remove `input: GFM` and that should set you back to kramdown which has the default you're looking for.

**Comment by mkirchner** [comment]
Well, yes, unless you want GFM fenced code blocks... ;-)

**Comment by xHN35RQ** [comment]
Since the GFM default is to interpret line breaks literally, setting `hard_wrap: false` is probably best left as a user-set option.

**Comment by xHN35RQ** [comment]
Jekyll 3.0 defaults to Rouge code highlighting and fenced code block support, so the following can be fully removed from `_config.yml`

```
markdown: Kramdown
kramdown:  
  input: GFM
  syntax_highlighter: rouge
```
