### ISSUE TITLE
An alternate Tufte Jekyll theme

### ISSUE THREAD

**Issue by xHN35RQ** [clayh53/tufte-jekyll#46]
There's a new Tufte-CSS Jekyll theme:

https://github.com/siawyoung/immaculate

Perhaps tufte-jekyll and immaculate might borrow and/or converge at some point to improve the Jekyll/Tufte experience for everyone.

**Comment by clayh53** [comment]
Interesting. It doesn't seem as feature complete as this repo yet, but I like how performance is one of the main concerns. Github blows my mind. The sheer number of projects is amazing.
