### ISSUE TITLE
Ordered lists fill full page

### ISSUE THREAD

**Issue by ekstroem** [clayh53/tufte-jekyll#49]
Hi,

Ordered lists seem to fill the full width of the page while unordered are rendered within the main column. Is there a way to make that consistent?

For example:

```
Check this out
* This is nice
* and looks fine
```
but

```
Check this out
1. This is not quite as nice
2. so what could be done?
```

I know of Tufte's aversion to lists but they are nice to explain, for example, steps in an algorithm.

**Comment by clayh53** [comment]
Probably just a matter of adding ul to the SCSS file.

**Comment by ekstroem** [comment]
Ah yes. That works. I added
```
ol { width: 45%;
     -webkit-padding-start: 5%;
     -webkit-padding-end: 5%;
    }
```
in case anyone else wants to do something like that.
