### ISSUE TITLE
The width of body is wider than 100% when the browser is wider than 800 px

### ISSUE THREAD

**Issue by quxiaofeng** [clayh53/tufte-jekyll#5]
In `tufte.css` line 209 - 211, when the screen exceeds 800 px, the width of the body is set to 95%.

```
@media screen and (min-width: 800px) {
  body {
    width: 95%; } }
```

However, in line 198 - 207, especially the line 204, the `padding-left` is set to 8.4%. It is OK that normally the body width is 87.5% and the whole width is only 87.5% + 8.4% = 95.9%. But when the `screen` width is larger than 800 px, the width of the rendered page is 95% + 8.4% = 103.4% and there will be a navigation bar appearing at the bottom of the browser.

Maybe the maximum width of the body should be 100% - 8.4% = 91.6%. Or the `padding-left` should be reduced.

**Comment by clayh53** [comment]
This should be fixed now in the new version
