### ISSUE TITLE
figcaption margin boxes aligning right instead of left

### ISSUE THREAD

**Issue by mmisiewicz** [clayh53/tufte-jekyll#50]
Fig captions appear to be centered oddly. If there is not enough text to wrap, they are aligning right. It seems to be something to do with a weird margin box. Example:

![screen shot 2016-06-19 at 13 07 19](https://cloud.githubusercontent.com/assets/1697413/16178746/00ecb2d2-361f-11e6-9967-2e9f87c62306.png)
![screen shot 2016-06-19 at 13 07 16](https://cloud.githubusercontent.com/assets/1697413/16178747/00f2e0a8-361f-11e6-9b03-9ea8c64b7f08.png)

It looks like use of figcaption was removed from Tuftecss in this commit:
https://github.com/edwardtufte/tufte-css/commit/70326956117d951c5c249b11a4529cea4cb67704

There was also discussion about its use here:
https://github.com/edwardtufte/tufte-css/issues/44

The problem seems to be mitigated by using a longer caption that forces wrapping.

**Comment by clayh53** [comment]
I think I have fixed this now.
