### ISSUE TITLE
Page Build Failed: Liquid Tag Not Recognized

### ISSUE THREAD

**Issue by joemouk** [clayh53/tufte-jekyll#52]
Thank you Clayh53 for making tufte-jekyll. I like your demo a lot, and I am trying to get it to work on my end. I am new to Jekyll and github. Please be patient with me. Your kindness is appreciated. 

I get the following error when trying to build the site on my github joemouk.github.io:

The page build failed with the following error:

The tag `math` on line 26 in `_posts/2015-10-03-Edge-Cases.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error.

I get the same error for sidenotes. I have not been able to load the page. I have tried to run it locally on my mac, but still have issues - it seems I can't download kramdown with El Capitan. 
Please let me know if you have any idea how I can get your well-designed tufte-jekyll to work for my blog.
Thank you very much.

**Comment by clayh53** [comment]
It sounds like you don't have an entire Jekyll build system installed. I am using Jekyll 3.1.3 and Kramdown 1.11.1 currently and getting no build errors. 

Have you installed RVM (Ruby Version Manager)? That is a big help in getting all your ruby gems built and synced up with various ruby versions. 

Getting a development system configured gets harder and harder on Mac OSX with its increased security measures that prevent installation of all the things you might need.

What error are you getting when you type in ```gem install kramdown```?

**Comment by joemouk** [comment]
Thank you so much for your prompt response. I really appreciate it.
I reinstalled RVM and Jekyll properly. It now works.

There was a issue with the welcome post, which I removed to get the site
running locally:
Liquid Exception: No header received back. in _posts/
2015-02-08-welcome-to-jekyll.md/#excerpt

I will start adding content, and I will keep you posted on any issues I
come across. I am so excited to be using this theme. It is great to have
Tufte inspired design on Jekyll, and I think this theme beats others I
found on other blogging platforms. It motivated me to use Jekyll in the
first place.
Thank you again for your hard work in creating this. And thank you for your
kindness in helping me.

**Comment by drhus** [comment]
unfortunately, Tufte Jekyll would work only locally because the use of Liquid markup tags https://github.com/Shopify/liquid , gh dosn't allow custom tags that >> https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/ i'm wondering if some fork implemented a workaround

**Comment by clayh53** [comment]
You will have to build the site locally, and then create a gh-pages branch for that repository, and push the compiled site to that branch. There are some scripts and utilities that will automate this process for you. One utility I use is jgd, which is on github.

**Comment by clayh53** [comment]
jgd here: https://github.com/yegor256/jekyll-github-deploy
