### ISSUE TITLE
maincolumn doesn't pass Markdown

### ISSUE THREAD

**Issue by sdruskat** [clayh53/tufte-jekyll#54]
Unlike `margin_figure.rb`, `main_column_img.rb` doesn't render Markdown in the figure caption.

Cf. `From Edward Tufte, *Visual Display of Quantitative Information*, page 92` in the [demo post](http://clayh53.github.io/tufte-jekyll/articles/15/tufte-style-jekyll-blog).

**Comment by andrashann** [comment]
Thanks @sdruskat for this solution, this was a paint point for me in this theme.
