### ISSUE TITLE
Build fail (colorator?)

### ISSUE THREAD

**Issue by davideriboli** [clayh53/tufte-jekyll#58]
Hi,
 I've just tried to build your theme under Ubuntu Xenial, using Jekyll 3.2.3 but this was the terminal output:

```
stormy@Stormbringer:~/GitHub/test$ jekyll build
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
      rouge (~> 1.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:34:in `block in setup': You have already activated colorator 1.1.0, but your Gemfile requires colorator 0.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:19:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:92:in `setup'
	from /var/lib/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /var/lib/gems/2.3.0/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'


```

**Comment by clayh53** [comment]
This sounds like a version mis-match to me. Let me check the Gemfile and make sure that there is not some specification that is too specific. This is a pretty vanilla theme and should compile easily.

C

**Comment by davideriboli** [comment]
If this can help my versions are:

- jekyll 3.4.3
- ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
- Bundler version 1.11.2

The only command I've launched was: `jekyll build`

**Comment by davideriboli** [comment]
Found!

1. I was missing a Javascript runtime = `sudo apt install nodejs`
2. Commands `jekyll build` and `jekyll serve` still not working = using `bundle exec jekyll build` and `bundle exec jekyll serve`.

Now everything works.
