### ISSUE TITLE
Would it be possible to only use $..$ and $$..$$ for inline and outline math?

### ISSUE THREAD

**Issue by iliveinhongkong** [clayh53/tufte-jekyll#59]
Currently using `{% m %}mathjax expression{% em %}` and  `{% math %}mathjax expression{% endmath %}` is way too painful...

As one user pointed out Jekyll's default Markdown renderer has built in mathjax support: http://kramdown.gettalong.org/math_engine/mathjax.html

**Comment by clayh53** [comment]
I have modified the repo to use $$.. $$ for MathJax expressions instead of the cumbersome custom Liquid tags
