### ISSUE TITLE
Using highcharter

### ISSUE THREAD

**Issue by ekstroem** [clayh53/tufte-jekyll#60]
I'm trying to get some of the `htmlwidgets` graphs to render in `tufte-jekyll`. I've looked at [Brendan Rocks' wonderful instructions](https://brendanrocks.com/htmlwidgets-knitr-jekyll/) and packages like `leaflet` and `dygraphs` render nicely. However, I'm having some problems with the `highcharter` package.

Here's my code:

    ---
    title: "Test"
    layout: post
    author: Me
    published: true
    comments: true
    tags:
    - reproducerbar forskning
    ---
    
    ```{r echo=FALSE}
    knitr::opts_chunk$set(screenshot.force = FALSE)
    ```
    
    ```{r echo=FALSE, message=FALSE}
    library(highcharter)
    hchart(LakeHuron)
    ```

Has anyone managed to get the `highcharter` package to work with Tufte-Jekyll

**Comment by ekstroem** [comment]
Oh .. I can add that if I include a `dygraphs` before `highcharter` then the `dygraph` renders nicely. If I swap the order then none of them work. Maybe the javascripts messes up?

**Comment by clayh53** [comment]
I suspect it has something to do with the jekyll markdown parser. I’m not sure on your example exactly how you are embedding the highcharter code. Have you looked at the generated output for that page from the jekyll build? 

Perhaps you need to wrap it in a <pre attribute=“0">…</pre> tag instead of the code tag that the triple backticks generates

**Comment by ekstroem** [comment]
The code is included as shown and embedding other htmlwidgets directly works nicely.
The output looks (at first glance) okay, and space is set on the page for the widget. An extended example of the finished page can be seen at 

http://sandsynligvis.dk/articles/16/test2.html

and as far as I can see the dependencies are correctly added to the page.

**Comment by clayh53** [comment]
When I check the console messages when looking at your page, I get the following:
[https://photos-5.dropbox.com/t/2/AABx-q4W1aLqcY-lcvir7ZMiKlSRYcuArIFzWBaaVc_nVQ/12/6214851/png/32x32/1/_/1/2/Screenshot%202017-06-11%2017.15.30.png/ELDD0QQYv6Q7IAcoBw/XlSApR_12ANMAqHQgBjFoHqnCwBMRaytBbL7XTmpM68?size=2048x1536&size_mode=3](url)

**Comment by ekstroem** [comment]
Hmm. I don't see that error when I look at the console. However, I found the problem: `jQuery` must be loaded *before* the the javascript for highcharter is loaded. When I swapped those around everything worked nicely, so I've moved that from the footer. 

Thanks for trying to help pin this down.
