### ISSUE TITLE
Header and footer suboptimal on small screens

### ISSUE THREAD

**Issue by reitzig** [clayh53/tufte-jekyll#8]
I decided to use this pretty theme for my website. After some tinkering, it does what I want it to in my Firefox. On my phone, I get this:

![screenshot_2015-09-22-13-53-02](https://cloud.githubusercontent.com/assets/4246780/10017863/311afe5e-6132-11e5-91e0-b6d0e46dc42b.png)
 
My suggestions:

  * The header should extend more gracefully, moving the line beneath the last navigation link.
    (The problem is probably that `nav.group` has a fixed height?)
  * The line distance between the social icons is too large.

**Comment by reitzig** [comment]
Steps to reproduce:

 1. Go [here](http://reitzig.github.io/)
 2. Resize the browser window to be very narrow.

**Comment by clayh53** [comment]
Thanks for pointing this out. I have been amazed at the interest in this little theme. I will add this to the list of things I need to sort out in the CSS. There is also an issue with some of the side-notes at some browser widths that I need to fix.

**Comment by reitzig** [comment]
Heh, I noticed that the CSS was slightly ... messy.

Once my site stabilizes, I'll try to distill a set of objective (i.e. not taste-specific) fixes out of it.

**Comment by clayh53** [comment]
The CSS is a trainwreck at the moment. I just took a look at Dave Leipman's CSS repo for this style and he has added some nice stuff that I would like to incorporate. Things such as real italic and bold font faces, and some modifications to link styling and so forth. I am going to be working on that along with some layout issues.

**Comment by reitzig** [comment]
Maintainability disturbs me more than design decisions at the moment. The latter is subject to taste, and if I can adapt things, no problem. But currently, it's hard to tell what gets which style.  
My advice: have exactly *one* `x { ... }` block per element. Redundancies resp. dependencies can be encoded using SASS (or so it appears, I have no experience with the tool).

**Comment by clayh53** [comment]
Check out the new version. I changed the header and footers
